### ISSUE TITLE
Ql-570 cut after each label is no longer available

### ISSUE THREAD

**Issue by feuerblitz2** [philpem/printer-driver-ptouch#11]
hello, 
i have a problem with the new version.  
Printer: Ql-570 The option to cut after each label is no longer available.  
now I often have pdf with hundreds of different labels.  
so far, cutting after each label has no longer worked 
with the new version no matter what I set.

**Comment by philpem** [comment]
Which specific version are you having problems with?

Which version was the last one you know worked?

What settings are you using to enable cut after every label?

**Comment by feuerblitz2** [comment]
tested with the debian package version printer-driver-ptouch (1.5.1-2) and printer-driver-ptouch (1.6-1)
the version printer-driver-ptouch (1.4.2-3) works

**Comment by feuerblitz2** [comment]
The setting is a combo box "AutoCut" with the options "Cut the medium at the end of the job", "Cut the medium after each label", "Do not cut the medium" I use "Cut the medium after each label" for version 1.4.2-3

**Comment by philpem** [comment]
I'll take a look at this on my QL-570 when I have a moment. I suspect the driver may be sending the wrong control codes between pages.

**Comment by feuerblitz2** [comment]
at the end of the file is cut correctly.  however, there is no cut between the individual levels.

**Comment by philpem** [comment]
ormally to achieve this you'd enable Auto Cut and Auto Eject (cut at end of job aka Chain Print Off), then set "Cut Every N labels" to 1. That would tell the printer to cut every single label.
Unfortunately it looks like the "Cut Every N" command is missing from the QL-570 printer definition in v1.5.1, so you can't set that option. Brother's documentation says that "cut every 1" is the default, but that's clearly not the case.

I've added the missing definition to the printer XML file. "Cut every N" now works for my QL-570. Can you confirm that it works on yours?

You'll need to remove the Debian package and build the latest git version from source. You may also have to remove and re-add your printer in the Printers control panel or CUPS.

**Comment by feuerblitz2** [comment]
It works again
