### ISSUE TITLE
Add 'where to go for software' in readme, pls.

### ISSUE THREAD

**Issue by bs27975** [philpem/printer-driver-ptouch#12]
Thank you for hosting this.

It means my (Linux) computer can understand my Brother labeler hardware.

However, it does not explain how to use / what software to use instead of the Windows Brother P-Touch (Quick) Editor that comes with the hardware. So, I can now connect the device, but I still can't use it (for no software).

I get that that is not the scope of this project - which people land at with simple searches such as '"Debian" "Brother" "P-Touch"'. However, their logical next question - what software to use, remains stymied.

It would be useful if the read me file contained a link to such software, or more likely, some known "How to use your P-Touch labeler under Linux" link / help article.

Search for such ... and one drowns in useless results.

Could someone kindly add a pointer or link in the readme file along the lines of: Try here for more information on how to use your Brother P-Touch labeler with Linux?

Such would likely save many a lot of frustration. (Part of the problems is discerning just which search terms are actually pertinent. Such a link would lead one towards figuring out appropriate search terms.)

Thanks for listening.

**Comment by philpem** [comment]
This is out of scope - you can use a lot of different software packages with the printer driver. I usually use gLabels, but I've heard it also works with LibreOffice and Inkscape.

Anything you can print with and set custom paper sizes should work.

**Comment by bs27975** [comment]
| This is out of scope

And that was my point.

All I was suggesting was for the person drowning in google results, give
them a quick sentence in the readme to help point them in a useful
direction.

e.g. Your mention of glabel here is perfect. It's a direction. Except ...
glabel google results note it works well with dymo printers, and not at all
with Brother. Since you seem to know differently, including that sentence
in the readme would be useful. I've also come across https://apz.fi/blabel/
, but I know nothing of it.

So, my only point was ... help a user out with a sentence or two in the
read me would be really useful.
