### ISSUE TITLE
Printing speed of multiple labels on a pre-cut labels tape

### ISSUE THREAD

**Issue by CimbaloMecoil** [philpem/printer-driver-ptouch#13]
I'm sending a print job for multiple labels on a pre-cut labels tape.
Between each label the printer (QL570) stops to align the labels tape, which increase the total printing time.
Using the ConcatPages option I get a continuos printing without stops (faster) but since it removes the margins the labels are out of alignment.
Is there an options to avoid stops and mantain the correct margins between labels?

**Comment by philpem** [comment]
Unfortunately there isn't. With the pre-cut labels, the printer needs to scan the alignment marks on the back of the label. Otherwise, as you've said, the printer loses alignment with the label stock.
Sadly this is an issue with the printer firmware.

**Comment by CimbaloMecoil** [comment]
Thanks for the quick response.
The Brother driver have different behaviour. It doesn't stop to scan the alignment marks on the back of the label.
I suppose the alignment error is neglegible or at least it doesn't build up too much.

From a quick look at the code I think the current behaviour is connected to this line of code:
https://github.com/philpem/printer-driver-ptouch/blob/master/rastertoptch.c#L1533
Do you have any suggestions?
