### ISSUE TITLE
Printer status/label size for networked printers

### ISSUE THREAD

**Issue by dottedmag** [philpem/printer-driver-ptouch#14]
There is a status request in protocol for USB-connected printers, however for my QL720-NW connected via TCP it does not work.

I have done some network sniffing and found out that manufacturer's utility to detect label size and printer status uses a separate protocol:

- Printer is available over SNMP
- Utility sends a SNMP request for label `.1.3.6.1.4.1.2435.3.3.9.1.6.1.0` (Brother private namespace)
- Printer answers with the 32 bytes of data laid out the same way as USB status `iS` response.

**Comment by philpem** [comment]
Hmm, I'm not sure what could be done on this. I think status monitoring is down to CUPS (or whatever printing system is in use). Certainly the Turboprint (and maybe Gutenprint too) drivers have a separate printer status display application.

Thanks for doing the legwork and documenting this - I'll keep this open as a reference, it's good to know even if I haven't got access to one of these printers to test with.
