### ISSUE TITLE
PT-P700 empty print

### ISSUE THREAD

**Issue by TheTimeWalker** [philpem/printer-driver-ptouch#16]
Hi!

I have tried using this driver with the PT-P700, but unfortunately it doesn't seem to work 100% correctly. The installation worked, and the printer is available with gLabels. However, it only prints an empty label with the 24mm Tape. I have tried using custom sizes on both printer settings and gLabels settings, change the orientation, etc. to no avail. I have checked with a Windows installation and the printer itself seems to be fine.

Is there anyway to somehow debug this?

**Comment by Sinclair732** [comment]
Same problem here installed Debian printer-driver-ptouch (1.5.1-2) package.
9mm is working, 24mm is empty. No Windows available for test.

**Comment by philpem** [comment]
@TheTimeWalker - you could use the Windows driver to print to file, then see if the "ptexplain" tool in this repository can correctly decode the output. Do the same with this driver and see if there are any differences.
Brother may have added something to the PT-P700 protocol which rastertoptch needs to handle differently to other printers.
They seem to have released a command reference for the PT-P700, which may help: https://download.brother.com/welcome/docp000771/cv_pth500p700e500_eng_raster_110.pdf

Unfortunately I don't have a PT-P700 and TZe tape to test with.

**Comment by TheTimeWalker** [comment]
Which is what makes it a bit weird. I have used the same PDF on both Windows and Linux with the same PDF reader, Okular, so that there should be as low amount of difference as possible. The PDF is just a simple 24 x 41 label which only has "TEST TEST" as text in it. That's what you see as "Raster graphics transfer" on Windows.

The Linux one just ignores this fully for some reason and does not contain any graphics transfer, only zero raster. Worse, it actually does waste the label, I get an empty 24 x 100 label out of it.

**Comment by TheTimeWalker** [comment]
Okay, so I can't say what changed but the printer now works properly. It's printing the text fine when I for example create a label on gLabels. Maybe ther was an update on CUPS or something else got fixed and now it's not an issue anymore. From my side, this seems to be resolved.

**Comment by philpem** [comment]
@M1cha - some of the printers do that. They have 18mm wide heads (128 dots if I remember correctly) but can take 24mm ribbon. The printed label fits in the middle of the ribbon.
