### ISSUE TITLE
How to add new devices

### ISSUE THREAD

**Issue by JulianGro** [philpem/printer-driver-ptouch#19]
I own a PT-D800W which actually works using the PT-P900W driver.
Is there any documentation on adding new devices? Or any interest on working through the thing with me?
From the very limited amount of testing I have done, the printer seems to work fine using the PT-P900W driver. The only thing that seems weird is that there is some dotting(?) when printing anything other than the test page. Straight lines look a bit as if they were aliased, exept for the ones on the test page.
I am connected to it via wifi and haven't tested USB.

**Comment by dynamodan** [comment]
Same question here, I have the D460BT, is there any info about which "older" driver might work with this machine?

**Comment by philpem** [comment]
@dynamodan, sadly you'll just have to try them. Look for printers which have similar specifications (print tape type, print width, auto cutter, etc) and try them.
