### ISSUE TITLE
Compile under OSX 12.6?

### ISSUE THREAD

**Issue by Claudenw** [philpem/printer-driver-ptouch#22]
Has anyone managed to compile under OSX 12.6?  Or have any suggestions?

**Comment by philpem** [comment]
Please note that the issues tab is for reporting bugs in the driver, not asking for support.

Sadly I don't know whether the driver can be built on OSX 12.6. I imagine it could be if the relevant packages were installed (you probably need XCode but anything else is a mystery to me).

You should also check that OSX 12.6 can use CUPS printer drivers.
