### ISSUE TITLE
OSX Ventura: make install does not seem to work properly

### ISSUE THREAD

**Issue by martinbogo** [philpem/printer-driver-ptouch#24]
I downloaded the latest release, then performed the following action after installing the command line tools for Xcode ( gcc, et. al. ) 

./configure
./make all install

The output was as follows:

`martin@Sumac ptouch-driver-1.6 % sudo make all install
Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)': 
Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)': 
/Library/Developer/CommandLineTools/usr/bin/make  all-am
make[1]: Nothing to be done for `all-am'.
 ./install-sh -c -d '/usr/local/lib/cups/filter'
  /usr/bin/install -c rastertoptch '/usr/local/lib/cups/filter'
 ./install-sh -c -d '/usr/local/share/foomatic/db/source/driver'
 /usr/bin/install -c -m 644 generated/driver/ptouch-pt.xml generated/driver/ptouch-ql.xml '/usr/local/share/foomatic/db/source/driver'
 ./install-sh -c -d '/usr/local/share/foomatic/db/source/opt'
 /usr/bin/install -c -m 644 generated/opt/Brother-PTQL-Align.xml generated/opt/Brother-PTQL-AutoCut.xml generated/opt/Brother-PTQL-ChainPrinting.xml generated/opt/Brother-PTQL-BytesPerLine.xml generated/opt/Brother-PTQL-ConcatPages.xml generated/opt/Brother-PTQL-CutLabel.xml generated/opt/Brother-PTQL-LabelPreamble.xml generated/opt/Brother-PTQL-LastPageFlag.xml generated/opt/Brother-PTQL-MinMargin.xml generated/opt/Brother-PTQL-MirrorPrint.xml generated/opt/Brother-PTQL-NegativePrint.xml generated/opt/Brother-PTQL-PixelTransfer.xml generated/opt/Brother-PTQL-Resolution.xml generated/opt/Brother-PTQL-Series.xml generated/opt/Brother-PTQL-SoftwareMirror.xml generated/opt/Brother-PTQL-TransferMode.xml generated/opt/Brother-PT-HalfCut.xml generated/opt/Brother-PT-LabelRecovery.xml generated/opt/Brother-PT-LegacyHires.xml generated/opt/Brother-PT-LegacyTransferMode.xml generated/opt/Brother-PT-Margin.xml generated/opt/Brother-PT-PageSize.xml generated/opt/Brother-QL-CutMark.xml generated/opt/Brother-QL-Margin.xml generated/opt/Brother-QL-MediaType.xml generated/opt/Brother-QL-PageSize.xml generated/opt/Brother-QL-PrintDensity.xml generated/opt/Brother-QL-PrintQuality.xml generated/opt/Brother-QL-StatusNotification.xml '/usr/local/share/foomatic/db/source/opt'
 ./install-sh -c -d '/usr/local/share/foomatic/db/source/printer'
 /usr/bin/install -c -m 644 generated/printer/Brother-QL-500.xml generated/printer/Brother-QL-550.xml generated/printer/Brother-QL-570.xml generated/printer/Brother-QL-650TD.xml generated/printer/Brother-QL-800.xml generated/printer/Brother-QL-810W.xml generated/printer/Brother-QL-820NWB.xml generated/printer/Brother-PT-PC.xml generated/printer/Brother-PT-18R.xml generated/printer/Brother-PT-550A.xml generated/printer/Brother-PT-E550W.xml generated/printer/Brother-PT-P700.xml generated/printer/Brother-PT-P900W.xml generated/printer/Brother-PT-P950NW.xml generated/printer/Brother-PT-1500PC.xml generated/printer/Brother-PT-1950VP.xml generated/printer/Brother-PT-1950.xml generated/printer/Brother-PT-1960.xml generated/printer/Brother-PT-2300.xml generated/printer/Brother-PT-2420PC.xml generated/printer/Brother-PT-2430PC.xml generated/printer/Brother-PT-2450DX.xml generated/printer/Brother-PT-2500PC.xml generated/printer/Brother-PT-2600.xml generated/printer/Brother-PT-2610.xml generated/printer/Brother-PT-3600.xml generated/printer/Brother-PT-9200DX.xml generated/printer/Brother-PT-9200PC.xml generated/printer/Brother-PT-9400.xml generated/printer/Brother-PT-9500PC.xml generated/printer/Brother-PT-9600.xml generated/printer/Brother-PT-9700PC.xml '/usr/local/share/foomatic/db/source/printer'`

I then restarted the CUPS subsystem by using 'sudo launchctl stop org.cups.cupsd' and 'sudo launchctl start org.cups.cupsd'

After the restart, I tried to add a USB label printer to the system ( PT-1950 ) and it does not show up as an option:

![Screenshot 2022-12-05 at 11 49 36 AM](https://user-images.githubusercontent.com/251177/205706906-d3d5460f-357c-4819-b1af-99cb81de1cf9.png)

Am I incorrectly installing the ptouch-driver?  Am I missing critical files ( foomatic? )

**Comment by martinbogo** [comment]
Further info -- I went into the web admin for CUPS to try to manually add the printer using the CUPS subsystem itself and this is the screenshot:

![Screenshot 2022-12-05 at 12 05 36 PM](https://user-images.githubusercontent.com/251177/205709991-009509ff-a125-4071-885e-77902f71dfdf.png)

Only the DCP and the MFC printers are showing up after the installation of the ptouch-driver.  Are the driver/config files for MacOS Ventura in a different location that /usr/local which is what the default ./configure uses?

**Comment by philpem** [comment]
Seems like you need a code signing certificate for Xcode. I'd suggest having a read of the Apple developer documentation - sadly this isn't something I'm able to help with.

**Comment by philpem** [comment]
I've asked a friend who uses OS X --

> > install Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)': Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)'
> 
> This seems to have to do with how their sudo is set up — I think they’re using a yubikey for sudo
> I don’t see anything else code signing related?
> On macOS, there generally is no need to sign code with an Apple certificate if the code will be run on the same machine that compiled it

So it looks like you may have some issue with your sudo setup. Other than that, I'm not sure.

**Comment by martinbogo** [comment]
*laugh*. sorry, I shouldn't have included that line in the dump... that's
just how I use 'sudo' -- yubikey auth instead of password.  That works
perfectly.

What's happening is that I am installing ( or attempting to install, I
should say ) using a standard configure/make all/make install and it
doesn't seem to make any difference as to what options I can use on OSX
Ventura ( 13.1 )

This is _definitely_ not a code signing problem.  The code runs just fine.
I can manually run the filter without issue.   The problem is that I think
the installation prefix used by default ( /usr/loca/ ) may not be correct.


The documentation for installing ptouch-driver is a bit thin...  using the
default configuration options may not be correct for Ventura?
