### ISSUE TITLE
QL700 not present in repo

### ISSUE THREAD

**Issue by MacBadger** [philpem/printer-driver-ptouch#32]
The most recent version include QL700 driver (v1.6)
installing via dnf and apt gives v1.5 (.1 i think)

This only gives footmatic options for the qL800 (which leads to filter issues if used with QL700) and QL510 (which doesn't have continuous paper length for the 700

Tried to build the 1.6 local on rPi, but also couldn't get this to work correctly.

**Comment by philpem** [comment]
Hi, can you please answer the following?

**Operating system and platform (please complete the following information):**
 - Operating system and distribution: [e.g. iOS, Debian, Ubuntu]
 - OS version [e.g. 22]
 - printer-driver-ptouch version (if you installed from a package e.g. RPM or Apt, this is the package version)
 - What software are you using to create and send the print job?


It seems like your operating system is using an outdated version of the driver -- if that's the case, then you need to uninstall your OS's version (for Raspberry Pi / Raspbian that would usually be `sudo apt remove printer-driver-ptouch`) then clone this repository and follow the instructions in the `INSTALL` file.

Generally speaking, that means running these commands in sequence: `./configure`, `make`, `sudo make install`.

**Comment by philpem** [comment]
Ahh - the problem is that the QL-700 driver is on the master branch, but isn't in a release yet.

I've just done a release of version 1.7, which should work for you.
