### ISSUE TITLE
Missing PT-P300BT and QL-600 in Makefile.am and rastertoptch.c

### ISSUE THREAD

**Issue by solbu** [philpem/printer-driver-ptouch#34]
Hi.
The XML files for PT-P300BT and QL-600 are missing from Makefile.am and rastertoptch.c.
This result in those files not being install on the user's system.

Is that intetional, or an oversight?

**Comment by philpem** [comment]
Will handle this in #33 :)

It's an oversight. I learned how to use Github templates this week, so there'll be one for printer driver PRs about updating `Makefile.am`.

The table at the top of `rastertoptch.c` is for Doxygen, which we don't currently generate. If it's wrong, it's in a comment and thus benign. The correct place to be looking for that information is the XML files, which is probably a pretty good argument for its removal...

**Comment by philpem** [comment]
Fixed in the V1.7 release and GIT HEAD :)
