### ISSUE TITLE
QL-600: Huge quality difference between Windows driver and this

### ISSUE THREAD

**Issue by V10lator** [philpem/printer-driver-ptouch#37]
![IMG_20230917_150455](https://github.com/philpem/printer-driver-ptouch/assets/1312422/8315ac36-0400-4e29-adae-77e4893b43d9)
The left one has been printed from a Windows VM while the right one has been printed from Linux using this driver. Both drivers had been configured to print in high-quality but as you see it's still day and night.

Here's the image file used for this:
![Ori-Ava](https://github.com/philpem/printer-driver-ptouch/assets/1312422/82447fd3-10ee-41ef-ba39-75e1d7227203)

**Comment by philpem** [comment]
This isn't a bug in the driver.

All the driver does is take the bitmap (1-bit black-and-white a.k.a. bitonal) data provided by CUPS and turns it into printer commands. The conversion from colour photo to bitonal is CUPS's doing -- or rather the PostScript renderer it uses (`pstoraster`).

The only way this could reasonably be improved is by rewriting `rastertoptch` as an 8-bit greyscale filter and implementing Floyd-Steinberg (and probably threshold) dithering in the driver itself. But if we're taking that route, the smarter money seems to be in adding P-Touch support to Michael R. Sweet's `lprint` driver: https://github.com/michaelrsweet/lprint/issues/15

**Comment by ValdikSS** [comment]
https://github.com/OpenPrinting/cups-filters/pull/642
