### ISSUE TITLE
Default ./configure settings causes CUPS to not show any ptouch printers, on Ubuntu 23.04

### ISSUE THREAD

**Issue by FroOkk** [philpem/printer-driver-ptouch#41]
**Describe the bug**
A clear and concise description of what the bug is:
When i compile the driver using ./configure without any additional parameters. It places its files under /usr/local. CUPS does not detect the driver at that path. However if i define the prefix /usr using "./configure --prefix=/usr" it places its installed files under /usr and that fixes the problem. CUPS then shows this driver's printer models in its list.

**To Reproduce**
1. Download and extract the 1.7 source tarball.
2. Run ./configure
3. Run make
4. Run sudo make install.
5. Check in CUPS printer list and find no printers supported by this driver.

**Expected behavior**
CUPS should show new printers in its driver list.

**Operating system and platform (please complete the following information):**
 - Operating system and distribution: [e.g. iOS, Debian, Ubuntu]
 Ubuntu
 - OS version [e.g. 22]
 23.04
 - printer-driver-ptouch version (if you installed from a package e.g. RPM or Apt, this is the package version)
 1.7 (compiled from 1.7 release source tarball)

I don't know if this is a driver bug, Ubuntu bug or user error. Please close if the fault lies elsewhere.

Sincerely
Frode Slatlem Okkenhaug

**Comment by philpem** [comment]
This is pretty much how things have always worked with the driver -- the prefix directory has to be specified. It's a CUPS thing.

There's probably a way to tell CUPS to look in `/usr/local` via a config file change, but it won't do so by default.
