### ISSUE TITLE
Pages per side defaults to 9

### ISSUE THREAD

**Issue by daftada** [philpem/printer-driver-ptouch#44]
The 'Pages per side' parameter under Print Properties -> Page Setup defaults to 9 where 1 is expected. I am using a Brother QL-570. My system defaults to another printer but, changing to the Brother to print, creates labels with teeny tiny print. Investigation showed it to be the 'Pages per side' parameter defaulting to 9. Switching this to the expected 1 gave labels with the intended font size.

**Comment by philpem** [comment]
Please provide the details requested in the bug report template.

https://github.com/philpem/printer-driver-ptouch/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
