### ISSUE TITLE
No cutter option

### ISSUE THREAD

**Issue by daftada** [philpem/printer-driver-ptouch#45]
Using a Brother QL-570 with tape media instead of pre-cut labels, the driver has no cutter options. So, printing multiple labels only triggers the cutter after the last label and not on each label as desired.

**Comment by philpem** [comment]
Please use the bug report template.

https://github.com/philpem/printer-driver-ptouch/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

As a minimum I need the operating system details.
