### ISSUE TITLE
Pages per side defaults to 9

### ISSUE THREAD

**Issue by daftada** [philpem/printer-driver-ptouch#46]
When opening the driver GUI for the first time the 'Pages per side' option of the 'Page setup' tab defaults to 9 instead of 1 as expected. This results in a teeny font.

**To Reproduce**
1) Go to Page iSetup tab in driver GUI.
2) Under 'Layout' on the left see the 'Pages per side' option which shows 9.

**Expected behavior**
Pages perside option should default to 1

**Screenshots**

**Operating system and platform (please complete the following information):**
 
 - OS version [e.g. 22] Raspbian GNU/Linux 11 (bullseye) armv
 -  Driver: ptouch:armhf/bullseye 1.5.1-2+b3
 - What software are you using to create and send the print job? gLabels
 - Label type: die-cut and continuous

**If you are reporting a print issue**
![ptouch-default](https://github.com/philpem/printer-driver-ptouch/assets/7712122/fe9eecf3-63f5-4abc-bc21-d639b9e52aa6)

**Additional context**

**Comment by philpem** [comment]
What printer is this on?

Firstly you should upgrade the "printer-driver-ptouch" package. I'm stunned Raspbian has version 1.5 in the repository, the latest is 1.7 and both Ubuntu and Mint are shipping at least 1.6 in current builds (I'm running 1.6-2).
  * https://repology.org/project/printer-driver-ptouch/packages
  * https://packages.debian.org/printer-driver-ptouch

Version 1.5 dates back to 2020 and may pre-date the extensive re-writing Andreas did. You should upgrade the "printer-driver-ptouch" package and see if that fixes your bug.


If for whatever reason you don't want to upgrade (again, you should), you can change this system-wide in the printer settings application.

I don't test on Raspbian but I would have expected it to behave the same as Debian Bullseye or another Debian derivative like Ubuntu or Mint.
