### ISSUE TITLE
To cutter option to support continuous label tape

### ISSUE THREAD

**Issue by daftada** [philpem/printer-driver-ptouch#47]
**Describe the bug**
No option for paper cutter. Printing multiples of a label has the cutter trigger after the last label but no option to cut each label printed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating system and platform (please complete the following information):**
 - Operating system and distribution: Raspbian GNU/Linux 11 (bullseye) armv
 - OS version [e.g. 22]
 - printer-driver-ptouch version: armhf/bullseye 1.5.1-2+b3
 - What software are you using to create and send the print job? gLabels
 - **If you are using a QL series (paper label) printer with continuous (not pre-cut or die-cut) labels:** Have you set up a custom page size for the label size you want? Yes

**If you are reporting a print issue**
Please provide (where possible) a test case, picture of the actual printed output, and a picture or description of the output you expected.
The test case can be a PostScript, PDF, or similar file - or an extract 

**Additional context**

**Comment by philpem** [comment]
@daftada Next time you submit a bug report, can you please fill out all the sections? It's helpful to know what you're doing at every step so I can reproduce bugs here.

Is this on the QL-570 printer per your previous issue?

The QL-570 is one of the printers I use here; I've not seen this issue but I don't think I have any continuous tape on hand.

With GLabels, you'll want to go to File -> Print then set:

  * Page setup tab: Paper type = Continuous length tape
  * Advanced tab: Finishing - check Auto Cut and Auto Eject

This should cut the print every label.

**Comment by daftada** [comment]
Hi,

Yes, it is the QL-570. I am using it with a Pi Zero original as a print
server using CUPS. I have updated ptouch driver to version 1.6 and made the
necessary adjustments to the cutter options via CUPS' printer management.
But it still won't cut between multiple label printing. The 'side per page'
option now defaults to 12 lol whereas previously it was 9. I just manually
adjust that for now. Strangely my Linux Mint desktop sees the networked
printer, but there are no 'finishing' options.

**Comment by philpem** [comment]
Please try the latest version - if you want to try the latest bleeding edge version:

```
sudo apt remove printer-driver-ptouch
sudo apt install build-essential autoconf automake
git clone https://github.com/philpem/printer-driver-ptouch.git
cd printer-driver-ptouch
./autogen.sh
./configure
make
sudo make install
```

Then delete and recreate the printer and try again. (you may need to restart CUPS)

**Comment by daftada** [comment]
MANY thanks for this.
How do I resolve this error please?
***@***.***:~/printer-driver-ptouch $ make
make  all-am
make[1]: Entering directory '/home/pi/printer-driver-ptouch'
gcc -DHAVE_CONFIG_H -I.  -D_GNU_SOURCE   -g -O2 -MT
rastertoptch-rastertoptch.o -MD -MP -MF .deps/rastertoptch-rastertoptch.Tpo
-c -o rastertoptch-rastertoptch.o `test -f 'rastertoptch.c' || echo
'./'`rastertoptch.c
rastertoptch.c:273:10: fatal error: cups/raster.h: No such file or directory
  273 | #include <cups/raster.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:550: rastertoptch-rastertoptch.o] Error 1
make[1]: Leaving directory '/home/pi/printer-driver-ptouch'
make: *** [Makefile:410: all] Error 2

**Comment by romainreignier** [comment]
> How do I resolve this error please?

```
sudo apt install libcups2-dev
```

**Comment by philpem** [comment]
@daftada , is this fixed in 1.7?

**Comment by daftada** [comment]
Feeling bad that I hadn't kept at it with the driver issue after all your
hard work, I scrapped my raspbian printer server and overwrote it with
Ubuntu. Version 1.7 was the apt default, and now it works perfectly. Thanks
to you. Pleased is an understatement.

Cheers,  Graham

**Comment by philpem** [comment]
> Feeling bad that I hadn't kept at it with the driver issue after all your hard work, I scrapped my raspbian printer server and overwrote it with Ubuntu. Version 1.7 was the apt default, and now it works perfectly. Thanks to you. Pleased is an understatement. Cheers, Graham

You're welcome! I'm glad you've got it working. I opened some issues earlier today re. page size issues and better documentation, so it's possible there'll be a 1.8 coming "soon".
