### ISSUE TITLE
Make fails on debian

### ISSUE THREAD

**Issue by CMALG** [philpem/printer-driver-ptouch#48]
**Describe the bug**
running make fails with some error

**To Reproduce**
1. download [v1.7](https://github.com/philpem/printer-driver-ptouch/releases/tag/v1.7)
2. extract 
3.  ./configure --prefix=/usr
4.  make

`make  all-am
make[1]: Entering directory '/home/pi/ptouch-driver-1.7'
./foomaticalize --srcdir=. --out=generated driver/ptouch-pt.xml driver/ptouch-ql.xml printer/Brother-QL-500.xml printer/Brother-QL-550.xml printer/Brother-QL-570.xml printer/Brother-QL-600.xml printer/Brother-QL-650TD.xml printer/Brother-QL-700.xml printer/Brother-QL-800.xml printer/Brother-QL-810W.xml printer/Brother-QL-820NWB.xml printer/Brother-PT-PC.xml printer/Brother-PT-18R.xml printer/Brother-PT-550A.xml printer/Brother-PT-E550W.xml printer/Brother-PT-P300BT.xml printer/Brother-PT-P700.xml printer/Brother-PT-P710BT.xml printer/Brother-PT-P900W.xml printer/Brother-PT-P950NW.xml printer/Brother-PT-1500PC.xml printer/Brother-PT-1950VP.xml printer/Brother-PT-1950.xml printer/Brother-PT-1960.xml printer/Brother-PT-2300.xml printer/Brother-PT-2420PC.xml printer/Brother-PT-2430PC.xml printer/Brother-PT-2450DX.xml printer/Brother-PT-2500PC.xml printer/Brother-PT-2600.xml printer/Brother-PT-2610.xml printer/Brother-PT-3600.xml printer/Brother-PT-9200DX.xml printer/Brother-PT-9200PC.xml printer/Brother-PT-9400.xml printer/Brother-PT-9500PC.xml printer/Brother-PT-9600.xml printer/Brother-PT-9700PC.xml opt/Brother-PTQL-Align.xml opt/Brother-PTQL-AutoCut.xml opt/Brother-PTQL-ChainPrinting.xml opt/Brother-PTQL-BytesPerLine.xml opt/Brother-PTQL-ConcatPages.xml opt/Brother-PTQL-CutLabel.xml opt/Brother-PTQL-LabelPreamble.xml opt/Brother-PTQL-LastPageFlag.xml opt/Brother-PTQL-MinMargin.xml opt/Brother-PTQL-MirrorPrint.xml opt/Brother-PTQL-NegativePrint.xml opt/Brother-PTQL-PixelTransfer.xml opt/Brother-PTQL-Resolution.xml opt/Brother-PTQL-Series.xml opt/Brother-PTQL-SoftwareMirror.xml opt/Brother-PTQL-TransferMode.xml opt/Brother-PT-HalfCut.xml opt/Brother-PT-LabelRecovery.xml opt/Brother-PT-LegacyHires.xml opt/Brother-PT-LegacyTransferMode.xml opt/Brother-PT-Margin.xml opt/Brother-PT-PageSize.xml opt/Brother-QL-CutMark.xml opt/Brother-QL-Margin.xml opt/Brother-QL-MediaType.xml opt/Brother-QL-PageSize.xml opt/Brother-QL-PrintDensity.xml opt/Brother-QL-PrintQuality.xml opt/Brother-QL-StatusNotification.xml
./printer/Brother-QL-600.xml:36: parser error : EntityRef: expecting ';'
  <url>https://support.brother.com/g/b/downloadhowto.aspx?c=us&lang=en&prod=lpql
                                                                   ^
./printer/Brother-QL-600.xml:36: parser error : EntityRef: expecting ';'
  <url>https://support.brother.com/g/b/downloadhowto.aspx?c=us&lang=en&prod=lpql
                                                                           ^
./printer/Brother-QL-600.xml:36: parser error : EntityRef: expecting ';'
tps://support.brother.com/g/b/downloadhowto.aspx?c=us&lang=en&prod=lpql600eus&os
                                                                                ^
./printer/Brother-QL-600.xml:36: parser error : EntityRef: expecting ';'
port.brother.com/g/b/downloadhowto.aspx?c=us&lang=en&prod=lpql600eus&os=130&dlid
                                                                                ^
./printer/Brother-QL-600.xml:36: parser error : EntityRef: expecting ';'
downloadhowto.aspx?c=us&lang=en&prod=lpql600eus&os=130&dlid=dlfp100718_000&flang
                                                                                ^
./printer/Brother-QL-600.xml:36: parser error : EntityRef: expecting ';'
wto.aspx?c=us&lang=en&prod=lpql600eus&os=130&dlid=dlfp100718_000&flang=178&type3
                                                                                ^
make[1]: *** [Makefile:1019: generated/stamp-h1] Error 255
make[1]: Leaving directory '/home/pi/ptouch-driver-1.7'
make: *** [Makefile:410: all] Error 2`

**Operating system and platform (please complete the following information):**
 - Operating system and distribution: Debian (Raspian)
 - OS version : Bullseye
 - printer-driver-ptouch version 1.7
 - Printer model: PT-P700

**Additional context**
Im not sure if that is a Raspian specific issue but to get to this point i had to install additional packages like described in this issue
https://github.com/philpem/printer-driver-ptouch/issues/42

    libcups2-dev
    libxml-perl
    libxml-libxml-perl

**Comment by lukasmichel** [comment]
sorry for bumping an old issue, but I just updated the Archlinux AUR-package to 1.7 and ran into this error when trying to build. 
Is the 1.7.1 release still planned?

**Comment by philpem** [comment]
Still planned but beyond this I don't think there's much to put in it - I'd like to get #52 dealt with before I push it out there.
