### ISSUE TITLE
Unable to create configure file with automake

### ISSUE THREAD

**Issue by marcschumacher** [philpem/printer-driver-ptouch#49]
**Describe the bug**
I am trying to generate the configure file as described in `INSTALL`, but I get the error
```
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
After running `./configure` which anyways got created, I get the following error:
```
❯ ./configure
./configure: line 2398: syntax error near unexpected token `-Wall'
./configure: line 2398: `AM_INIT_AUTOMAKE(-Wall -Wno-portability)'
```

**To Reproduce**
1. Download the repo to a local folder
2. Move into the folder using `cd`
3. Run `autoconf`
4. Run `./configure`

**Expected behavior**
The configure file should be generated without errors. The generated `./configure` file should not create an error.

**Operating system and platform (please complete the following information):**
* MacOS Sonoma 14.4.1 (23E224)
* Autoconf 2.72

**Additional context**
I found [this article on Stackoverflow](https://stackoverflow.com/questions/16188335/automake-error-no-proper-invocation-of-am-init-automake-was-found) stating that the configuration in `configure.am` should not contain both `AC_INIT` and `AM_INIT_AUTOMAKE`. Is that possibly something to fix?

**Comment by philpem** [comment]
Unfortunately I don't have an OSX Sonoma system to test with.

The installation instructions are just generic ones which Autoconf installs.

If you're building from a Git checkout, you need to run "autogen.sh" to rebuild the configure script. This should fix the issue.
