### ISSUE TITLE
How to build from source on Raspberry Pi 4 (aarch64)?

### ISSUE THREAD

**Issue by Danrancan** [philpem/printer-driver-ptouch#50]
The install file doesn't list any needed dependancies to build this from source. It also doesn't have instructions on how to build this driver for the Raspberry Pi 4 arm64 devices. Is it possible to build this for ARM and if so, how? What are the dependancies and build commands? Thanks.

**Comment by philpem** [comment]
I thought there were build instructions in the README but apparently not ...

There's no reason why it wouldn't work. Debian are building for it on the Bookworm and Sid releases.

Ideally you should be installing from your distribution's packages (if they're up to date). You may need to enable backports.

If you want to build from source, you need to run:
```
git clone https://github.com/philpem/printer-driver-ptouch.git
cd printer-driver-ptouch
./autogen.sh
./configure --prefix=/usr
make
sudo make install
```

I don't have a firm list of build dependencies but these are from the Debian package:

```
 foomatic-db-engine (>= 4.0.13-5),
 libcups2-dev,
 libcupsimage2-dev,
 libxml-libxml-perl,
 pyppd,
```

The Debian package is here, and the files they provide may give you an idea how to build and install this: https://packages.debian.org/trixie/printer-driver-ptouch
