### ISSUE TITLE
Bug in QL-800 XML Driver File

### ISSUE THREAD

**Issue by stevenlgreen00** [philpem/printer-driver-ptouch#9]
Bug: The XML file does not specify ULP transfer mode like the lower numbered QL printers.

```
<option id="opt/Brother-PTQL-PixelTransfer">
      <enum_val id="ev/RLE" sense="false" />
      <enum_val id="ev/ULP" />
</option>

```
Adding this to the Printer XML file for the QL-800 enables printing.

**Comment by philpem** [comment]
This seems to have wider effect than just the QL-800 - the QL-800 series manual (https://download.brother.com/welcome/docp100278/cv_ql800_eng_raster_100.pdf) indicates that this whole series uses ULP, but also supports optional RLE compression on top of ULP.

I'm about to push a fix for this, which will fix the QL-800, QL-810W and QL-820NWB.

Unfortunately I don't have any of those printers to test with, so would appreciate feedback from users about whether this fix works.
